name: Build

on:
  push:
    branches:
      - main
      - 4.x
  pull_request:
    branches:
      - main
      - 4.x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B clean install
